### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by WangHelin1997** [RetroCirce/Zero_Shot_Audio_Source_Separation#1]
Hi, authors. When will the code be released? 
Thanks.

**Comment by RetroCirce** [comment]
Hi, 

we are pushing the process of the open source. 
I think it will be released within January (perhaps around 15th-25th)

Thanks

**Comment by RetroCirce** [comment]
New Update: we got the open source permission.
The code will be released before Feb 1st in this repo.
Thank you for your waiting!
