### ISSUE TITLE
Possible to run on CPU only ?

### ISSUE THREAD

**Issue by bubblegg** [RetroCirce/Zero_Shot_Audio_Source_Separation#10]

**Comment by RetroCirce** [comment]
Possibly can use cpu for just inference (definitely not for training), I never try it. And make sure you have at least 16 GB memory.

Then you revise the line 227 as:
`trainer = pl.Trainer (
      accelerator="cpu",
      gpu = None
)
`

**Comment by bubblegg** [comment]
Thank you so much !
