### ISSUE TITLE
Total lenght of 'dataloader' across ranks is zero. Please make sure that it returns at least 1 batch.

### ISSUE THREAD

**Issue by lucellent** [RetroCirce/Zero_Shot_Audio_Source_Separation#16]
This is weird, it was working a few days ago when it suddenly spit out this error. In my understanding it's suggesting that the (reference) samples are not enough? Even though I'm using the same song and samples as prior to this error, I haven't changed anything

**Comment by lucellent** [comment]
(accidentally closed the issue, sorry)

**Comment by RetroCirce** [comment]
Hi，

You said that the code ran well a few days ago but now it comes out some errors?

I think the problem possibly comes from your data. Your error log basically says that the model cannot find enough data to separate or query. You probably need to check how much your data’s duration is, or how many samples you have.

**Comment by lucellent** [comment]
Imagine I separated a song into L and R channels (since zero-shot only works with mono audio) and there are 3 samples in my sample folders, with different lenghts.

I successfully used zero-shot for the R channel file, but then when I tried to run the L channel file, that's when it started giving me the error

That's what I mean by I didn't change anything

**Comment by RetroCirce** [comment]
Would you send me the file of your samples? If the model works well on your L channel file, I believe there must be something wrong with your R channel file.

**Comment by lucellent** [comment]
I already deleted them sadly, but still - I exported both the same way and with same settings

I could send you the files I tried to run today if that will work also

**Comment by RetroCirce** [comment]
Sure, you can send it to me and let me check

**Comment by lucellent** [comment]
https://we.tl/t-hmjs4k6FKO

**Comment by lucellent** [comment]
Ah, something came to my mind - I just exported the sample in 16bit wav, it was previously 32 bit mp3... it works now

Was it because it was a 32bit file? I don't usually work with such

**Comment by RetroCirce** [comment]
Aha, I think the problem might lie in here. I used the librosa audio library to process the audio. By default it might process on 16bit file (I’m not sure). The error says it cannot find any data so it possibly is because the librosa does not process the 32bit file and output none. But i think this can be revised by changing hyperparameters. You can Google it to see more details. 

Glad to hear that you fix this problem!
