### ISSUE TITLE
Colab notebook?

### ISSUE THREAD

**Issue by audiomax-ai** [RetroCirce/Zero_Shot_Audio_Source_Separation#19]
Are there any plans to create a Colab notebook for this model?

**Comment by RetroCirce** [comment]
Hi, currently we do not plan to have the colab notebook.
Some people made a colab but perhaps needs more revision: https://colab.research.google.com/drive/1kUj5DQe6HzkPo4WyWYTVfHZg14FyTgZY?usp=sharing
