### ISSUE TITLE
ERROR: Unexpected bus error encountered in worker.

### ISSUE THREAD

**Issue by gitkeymaster** [RetroCirce/Zero_Shot_Audio_Source_Separation#20]
I get this error running the model on replicate for a 5 minute song (If I truncate the song to 1 minute it works.)

 Any ideas?

ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).

**Comment by RetroCirce** [comment]
Hi,

Sorry for the delay reply, pretty busy these weeks.
When I process the 5-min song, the process is successful.
When the error is encountered is worker, I assume you could reduce the numworker to see if it goes well. And check the GPU memory and RAM to see if one of them exceed.
