### ISSUE TITLE
Can't use overlap + clicks issue

### ISSUE THREAD

**Issue by lucellent** [RetroCirce/Zero_Shot_Audio_Source_Separation#21]
"raise "ffmpeg does not exist. Install ffmpeg or set config.overlap_rate to zero."
TypeError: exceptions must derive from BaseException"

Yes, I have ffmpeg installed

Basically that's it. I tried overlap 1.0 but it doesn't seem to work, 0.0 works though.

I wanted to try it because the outputs always have periodic clicks in them

![image](https://user-images.githubusercontent.com/38135928/235533329-a2f886ec-be52-4d91-bcf1-8b26778db820.png)

**Comment by lucellent** [comment]
0.9 works and gets rid of the click issue... weird why 1.0 doesn't work, but it's not a big issue

**Comment by RetroCirce** [comment]
Because 1.0 is completely overlapping, meaning that the current chunk is 100% overlapped with the previous chunk  --> the time cursor will not go forward.
