### ISSUE TITLE
Poor results (and doubt)

### ISSUE THREAD

**Issue by lucasbr15** [RetroCirce/Zero_Shot_Audio_Source_Separation#5]
Hello how are you?

Finally with your explanations I managed to use Zero Shot ASS,

However, when examining the results, using the test keys "vocals",

I got unattractive results, I didn't understand why, being that in the examples of the videos they sound very good,

So my question is as follows,

In the "Data/Query" folder, to get decent results, how many examples should I put there?

Because I did as follows,

In "mixture.wav" is the complete instrumental with the vocals,

And in the "Query" folder I put 15 examples of clean vocals (from the singer in question),

So am I doing it wrong?

NOTE: Each example is on average 7 to 15 seconds long in .wav format

I tested it on other examples and got the same pattern (unattractive results),

When I refer to unattractive results, I mean almost no final changes, the files in the "wavoutput" folder are practically unmodified.

I only tested the model (htsat_audioset_2048d.ckpt) because the other two models are incompatible with this code, I received checkpoint errors (because the script is not standardized to accept them).

So if you can let me know why I would be grateful,

My thanks in advance,

Lucas Rodrigues.

**Comment by lucasbr15** [comment]
Here is an example using 'guitar'

My "data" and "wavoutput" folder:
https://drive.google.com/drive/folders/1ERU6XCgjW4jzJEhPDQvoqKhkthCqRdLo?usp=sharing

in config.py i used: test_key = ["guitar"] ,,, and checkpoint used model: htsat_audioset_2048d.ckpt 

Tell me if it's right, or if I'm doing something wrong, thanks.

**Comment by RetroCirce** [comment]
Hi Lucas,

I use your guitar query and get this result (only with the 1,wav as the query and your teste.wav as the mixture: 
https://drive.google.com/file/d/1fSMu83JBhWvg4VEdm6CKn4yOpWrJGISm/view?usp=sharing

I think this is the right result. Your result seems to have no different from your original audio, there must be something wrong in your code.

I attach my config.py for you, to see there is something wrong:
https://drive.google.com/drive/folders/1BMkSZRLvKx1M3upTXXiNH2El4CqoLHmF?usp=sharing

best,
Ke
