### ISSUE TITLE
Doubt about increasing samples (Query)

### ISSUE THREAD

**Issue by lucasbr15** [RetroCirce/Zero_Shot_Audio_Source_Separation#7]
Would it be possible to increase the examples in the Query folder? I noticed that when I put more than 74 .wav files I get this error: "ZeroDivisionError: integer division or module by zero".

So I would like to know if it is possible to increase the samples, thanks again.

**Comment by RetroCirce** [comment]
Hi,

Yes, theoretically it support the "unlimited" query examples, the maximum number I used is 100.
The error you met is probably not the load problem but the wavfile problem itself, maybe there is a segment/slice of the wavfile contain all zeros? You can find the error code line to see if there is further information.
