### ISSUE TITLE
Is it possible to have result sound kept for each individual sample ?

### ISSUE THREAD

**Issue by bubblegg** [RetroCirce/Zero_Shot_Audio_Source_Separation#8]
During my testing, I found out that 6 samples in one sample folder versus 6 individual separations give different results and I assume this is because of some kind of generalization (i don't know how this works :P). Also found this out one time when I put 500 instrument samples the output was basically NULL. 

Is there any mode or a script in the code that could change it for example to include audio out of each sample extraction in one mixdown file or at least every sample having its output file it would make things so much easier for me instead of doing it manually because this method serves me better for things I'm testing. 
(i tried gather mode, I don't know if that's the idea but output still doesn't seem to equal 6 individual sample inferences combined)
Thank you!

**Comment by RetroCirce** [comment]
Let me understand what you want to do: do you want to use 6 queries samples to separate the mixture audio 6 times separately instead of only separating 1 time with 6 queries average embeddings?

**Comment by bubblegg** [comment]
Yes i think that is corect.

**Comment by bubblegg** [comment]
(1) Take a look at main.py from line 232-246, where we send all query samples into the "AutoTaggingWrapper" to get their average embeddings. Here, you need to take a look at asp_model.py from line 692-702, the code to output the average embedding, you need to revise it to output each query embedding. Then you return to main.py, you could get the embedding of all query samples, such as "all_queries".

I apologize but my knowledge in reading and understanding code is pretty much 0. I doubt I can do it myself sadly :(. 
I think I can only request if you would like to modify the code for solution (1) and paste it here if you would like to.

**Comment by RetroCirce** [comment]
Get it! I will find a time to make it, possibly in the beginning of March.
